spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # custom config for queue (exchange with the same name created by default)
  rabbitmq-first-queue: my_queue_1
  rabbitmq-second-queue: my_queue_2